# Generated by Django 5.2.5 on 2025-08-10 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iata",
                    models.CharField(
                        db_index=True,
                        help_text="3-letter IATA airport code ('GRU' or 'JFK')",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City where airport is located", max_length=100
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Latitude coordinate for distance calculations",
                        max_digits=10,
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Longitude coordinate for distance calculations",
                        max_digits=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="State/Province (mainly for domestic airports)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this airport is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_sync",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last time this record was synced from the API",
                    ),
                ),
            ],
            options={
                "db_table": "airports",
                "ordering": ["iata"],
                "indexes": [
                    models.Index(fields=["iata"], name="airports_iata_592379_idx"),
                    models.Index(fields=["city"], name="airports_city_2f0293_idx"),
                    models.Index(
                        fields=["is_active"], name="airports_is_acti_222b5a_idx"
                    ),
                    models.Index(
                        fields=["last_sync"], name="airports_last_sy_24148c_idx"
                    ),
                ],
            },
        ),
    ]
